name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build Binary
      run: |
        docker build . -t builder
        docker run --rm -v ${PWD}:/project builder make
    - uses: actions/upload-artifact@master
      with:
       name: envSwap
       path: "./dist/wiiu"
