name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build Binary
      run: |
        docker build . -t builder
        docker run --rm -v ${PWD}:/project builder make
        export VERSION=$(make get_version)
    - uses: actions/upload-artifact@v3
      with:
        name: EnvSwap-${{ vars.VERSION }}
        path: "./EnvSwap-${{ vars.VERSION }}.zip"
