name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up devkitPro
        run: |
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo pacman -S --noconfirm devkitARM devkitPPC wut

      - name: Set up libmocha
        run: |
          git clone https://github.com/wiiu-env/libmocha
          cd libmocha
          make install

      - name: Build project
        run: make
